#ifndef QTGUIINSPECTOR_GLOBAL_H
#define QTGUIINSPECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTGUIINSPECTOR_LIBRARY)
#  define QTGUIINSPECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTGUIINSPECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTGUIINSPECTOR_GLOBAL_H
